export const ERROR_PHONE_FORMAT = 'Неправильный формат'
export const ERROR_AGREEMENT = 'Пожалуйста, подтвердите соглашение'
export const ERROR_EMPTY = 'Пожалуйста, заполните поле'
export const ERROR_CODE = 'Неправильный код'
export const ERROR_CODE_EXPIRED = 'Срок ожидание истек. Нажмите на "Повторно отправить СМС"'
export const ERROR_PHONE = 'Неверный номер телефона. Пожалуйста измените'
export const ERROR_PHONE_REGISTER = 'Пользователя не существует. Введите данные о себе'
export const ERROR_EMAIL_FORMAT = 'Неправильный формат email'
export const ERROR_LOCATION_FORMAT = 'Введите все 4 пункта. Если пункт отсутствует введите прочерк "-"'
export const ERROR_HAVE_LOCALITY = 'Неккоректный город'
export const ERROR_HAVE_COUNTRY = 'Неккоректная страна'
export const ERROR_DELIVERY = 'Выберите доставку'

